# Generated by Django 4.2.16 on 2025-01-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databeachvolley', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'databeachvolley_contenido',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'databeachvolley_grupo',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'databeachvolley_sesion',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('0', 'entrenador'), ('1', 'estadistico'), ('2', 'jugador')], max_length=12),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='databeachvolley_usuario',
        ),
        migrations.CreateModel(
            name='Invitaciones',
            fields=[
                ('id_invitacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('dni_invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('dni_invitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo')),
            ],
            options={
                'db_table': 'databeachvolley_invitaciones',
            },
        ),
        migrations.CreateModel(
            name='GrupoActivo',
            fields=[
                ('dni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo')),
            ],
            options={
                'db_table': 'databeachvolley_grupo_activo',
            },
        ),
        migrations.CreateModel(
            name='Registra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.contenido')),
            ],
            options={
                'db_table': 'databeachvolley_registra',
                'unique_together': {('id_contenido', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo')),
            ],
            options={
                'db_table': 'databeachvolley_pertenece',
                'unique_together': {('id_grupo', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='Envia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.contenido')),
            ],
            options={
                'db_table': 'databeachvolley_envia',
                'unique_together': {('id_contenido', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='CreaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.sesion')),
            ],
            options={
                'db_table': 'databeachvolley_crea_sesion',
                'unique_together': {('id_sesion', 'dni')},
            },
        ),
        migrations.CreateModel(
            name='CreaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo')),
            ],
            options={
                'db_table': 'databeachvolley_crea_grupo',
                'unique_together': {('id_grupo', 'dni')},
            },
        ),
    ]
