# Generated by Django 4.2.16 on 2025-01-09 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databeachvolley', '0002_contenido_grupo_sesion_alter_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creagrupo',
            name='dni',
            field=models.ForeignKey(db_column='dni', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creagrupo',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo'),
        ),
        migrations.AlterField(
            model_name='grupoactivo',
            name='dni',
            field=models.OneToOneField(db_column='dni', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupoactivo',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo'),
        ),
        migrations.AlterField(
            model_name='invitaciones',
            name='dni_invitado',
            field=models.ForeignKey(db_column='dni_invitado', on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitaciones',
            name='dni_invitador',
            field=models.ForeignKey(db_column='dni_invitador', on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitaciones',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo'),
        ),
        migrations.AlterField(
            model_name='pertenece',
            name='dni',
            field=models.ForeignKey(db_column='dni', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pertenece',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='databeachvolley.grupo'),
        ),
    ]
