# Generated by Django 4.2.16 on 2025-01-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databeachvolley', '0003_alter_creagrupo_dni_alter_creagrupo_id_grupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pertenece',
            options={'managed': False},
        ),
    ]
