# Generated by Django 4.2.16 on 2025-01-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databeachvolley', '0004_alter_pertenece_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creagrupo',
            options={'managed': False},
        ),
    ]
